### ISSUE TITLE
Add action to write a string on a text file

### ISSUE THREAD

**Issue by miccol** [mjyc/concodeit#15]
Hi,
Thank you for developing ConCodeit! 
Is it possible to add an action that writes a string on a text file?

Thanks

**Comment by mjyc** [comment]
It might be challenging because the ConCodeIt is design to run on a browser.

I would start from looking at how a similar block is implemented, e.g., `say`. You'd need to add a block definition:

1. https://github.com/mjyc/concodeit/blob/master/pkgs/waitfor/index.html#L88-L94
2. https://github.com/mjyc/concodeit/blob/master/pkgs/waitfor/src/index.js#L125-L140
3. https://github.com/mjyc/concodeit/blob/master/pkgs/waitfor/src/index.js#L489-L497

You probably want to edit 3. and figure out how to write a string to a file in a browser environment here. I guess you can download a file that contains the specified string but I guess that's not what you want.. Sorry, I don't have a solution I can think of on top of my head.

Anyways, more detailed explanations can be found on the official blockly website but let me know if you need more pointers.
